### PR TITLE
Feature/tl injector - fixes #4 Generate Traffic Light emulator function

### LINKED ISSUE #4: Generate Traffic Light emulator function.
Create a component to generate /traffic_waypoint emulated data. Can be simple user keyboard control to indicate a traffic light at fixed point ahead, and another key to clear. 

This will allow clean forward progress on two parts of the project at the same time.

### PR DESCRIPTION
**Pull request by AntoniaSophia**
This is a first version of the traffic light injector, fixes #4 

It is a separate ROS node called TLInjector (located in file tl_injector.py).

**NOTE: I've not used the original topic /traffic_waypoint but created a new one called /traffic_waypoint_injection --> contains the closest waypoint as well as the color of the traffic light**

How to run the TL injector ?

-    use the Docker environment
-    attach a new console to a running Docker instance
-    run the injector as separate ROS node
-    type 'r' or 'y' or 'g' (or 'x' to stop the injector)
-    subscribe to topic /traffic_waypoint_injection

Example:
./attachToContainer.sh
./runTL_injector.sh
r

- type 'r' in order to inject a red traffic light
- type 'y' in order to inject a yellow traffic light
- type 'g' in order to inject a green traffic light
- type 'x' in order to stop the TL injector

### CODE REVIEW

**Review by peterbarry — COMMENTED** [review]
Hi @AntoniaSophia , 
I used latest docker image, and in a seperate attach

I get the following error:
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://4717368b329e:33423/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    tl_injector (tl_injector/tl_injector.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
ERROR: cannot launch node of type [tl_injector/tl_injector.py]: can't locate node [tl_injector.py] in package [tl_injector]
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete
root@4717368b329e:/capstone/ros#

**Comment by AntoniaSophia** [comment]
Sorry, this seems to be again a problem with the access rights of the file system..... hope this fix now works (just made an update on feature branch).
Please try out and let me know whether it works now!

**Comment by peterbarry** [comment]
I'm getting an error when trying to echo.

-----------------------------------------------------------
root@1f323436f295:/capstone/ros# rostopic list
/base_waypoints
/current_pose
/current_velocity
/final_waypoints
/image_color
/rosout
/rosout_agg
/tf
/tf_static
/traffic_waypoint
/traffic_waypoint_injection
/twist_cmd
/vehicle/brake_cmd
/vehicle/steering_cmd
/vehicle/throttle_cmd
/vehicle/traffic_lights
root@1f323436f295:/capstone/ros# rostopic info /traffic_waypoint_injection 
Type: styx_msgs/TrafficLightDetection

Publishers: 
 * /tl_injector (http://1f323436f295:37369/)

Subscribers: None


root@1f323436f295:/capstone/ros# rostopic echo /traffic_waypoint_injection 
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
ERROR: Cannot load message class for [styx_msgs/TrafficLightDetection]. Are your messages built?
root@1f323436f295:/capstone/ros# 
root@1f323436f295:/capstone/ros# 
root@1f323436f295:/capstone/ros# rostopic info /traffic_waypoint
Type: std_msgs/Int32

Publishers: 
 * /tl_detector (http://1f323436f295:46745/)

Subscribers: None


root@1f323436f295:/capstone/ros# rostopic echo  /traffic_waypoint


^Croot@1f323436f295:/capstone/ros# rostopic echo /traffic_waypoint_injection 
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
**ERROR: Cannot load message class for [styx_msgs/TrafficLightDetection]. Are your messages built?**
root@1f323436f295:/capstone/ros# rostopic info /traffic_waypoint_injection 
Type: styx_msgs/TrafficLightDetection

Publishers: 
 * /tl_injector (http://1f323436f295:37369/)

Subscribers: None

**Comment by peterbarry** [comment]
By the way.. No "sorry" or apologizes.. needed.. your really getting us going!! thanks

**Comment by AntoniaSophia** [comment]
Did you run ./runme.sh in the docker imstance before?

**Comment by peterbarry** [comment]
Hi, Yes I did.. steps
check out your branch.
./builddocker.sh
./rundocker
in the docker :
> runme.sh

attached to a docker : 
 >runTL_injector.sh

attache to docker
> rostopic info your-topic..
Others are ok

This is the log from your generator.
peter@peter-MacBookAir:~/project/car-nd-capstone$ ./attachToContainer.sh 
root@9003dd6961a3:/capstone/ros# ls
build  devel  initCapstone.sh  launch  runTL_injector.sh  runme.sh  src
root@9003dd6961a3:/capstone/ros# ./runTL_injector.sh 
... logging to /root/.ros/log/473ec7e8-c7eb-11e7-82e6-0242ac110002/roslaunch-9003dd6961a3-592.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://9003dd6961a3:46339/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    tl_injector (tl_injector/tl_injector.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[tl_injector-1]: started with pid [610]
[DEBUG] [1510519906.704712]: init_node, name[/tl_injector], pid[610]
[DEBUG] [1510519906.705383]: binding to 0.0.0.0 0
[DEBUG] [1510519906.705786]: bound to 0.0.0.0 36903
[DEBUG] [1510519906.706482]: ... service URL is rosrpc://9003dd6961a3:36903
[DEBUG] [1510519906.706914]: [/tl_injector/get_loggers]: new Service instance
[DEBUG] [1510519906.709993]: ... service URL is rosrpc://9003dd6961a3:36903
[DEBUG] [1510519906.710567]: [/tl_injector/set_logger_level]: new Service instance
[DEBUG] [1510519906.771740]: connecting to 9003dd6961a3 42447
                                                             [DEBUG] [1510519906.772345]: connecting to 9003dd6961a3 40239

**Comment by AntoniaSophia** [comment]
Thanks for the feedback!! Indeed there was another problem which I've fixed in the package.xml in order to build all messages. 
In the attached instance try to run injector first and then inspect the topic with command
source devel/setup.sh ; rostopic echo /traffic_waypoint_injection
Please use source devel/setup.sh everytime you attach a console to the container. 
This should work hopefully -crossing fingers... ;-)

**Comment by peterbarry** [comment]
Almost there. Followed instructions  above, including - Please use source devel/setup.sh everytime you attach a console to the container. Note: I dont have the simulator started yet.

When I press a key in the generator, if crashes.
eg press g

                                          Traceback (most recent call last):
  File "/capstone/ros/src/tl_injector/tl_injector.py", line 137, in <module>
    TLInjector()
  File "/capstone/ros/src/tl_injector/tl_injector.py", line 77, in __init__
    injectorMsg.waypoint = self.get_closest_waypoint(self.pose.pose)
AttributeError: 'NoneType' object has no attribute 'pose'
[DEBUG] [1510599243.373317]: connecting to 6f668144588d 35405
[tl_injector-1] process has died [pid 629, exit code 1, cmd /capstone/ros/src/tl_injector/tl_injector.py __name:=tl_injector __log:=/root/.ros/log/f23adcb4-c8a3-11e7-a80a-0242ac110002/tl_injector-1.log].
log file: /root/.ros/log/f23adcb4-c8a3-11e7-a80a-0242ac110002/tl_injector-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by AntoniaSophia** [comment]
Ok, next try..... Great that you really test before you merge any crap from us!! :-)

**Review by peterbarry — APPROVED** [review]
Good to go, tested with simulator running and not.

**Pull request merged**
