### PR TITLE
Feature waypoint partial

### PR DESCRIPTION
**Pull request by ahmedzikry0**

### CODE REVIEW

**Comment by AntoniaSophia** [comment]
I just have some questions:
1) do we also have those detailed waypoint list on Carla?

2) the waypoint list has to be converted to a trajectory using spline approximation and vehicle speed, right? Or do we use JMT and target duration?  

3) you also have implemented a function getClosestWaypoint() - I have implemented same in TL_injector. we should refactor in order to use only one of them. Both look good, for me it’s fine if we take yours (as long as you have not cut&paste it from anybody‘s repo :-))

**Comment by AntoniaSophia** [comment]
Implementation looks good from my perspective (i‘m on the road currently and can only perform a visual review via smartphone)

**Review by peterbarry — COMMENTED** [review]
Is there a possibility that you return a nearest point behind the vehicle?

**Comment by peterbarry** [comment]
approving for merge.

**Review by peterbarry — APPROVED** [review]

**Pull request merged**
