### PR TITLE
Wip dbw update angular

### PR DESCRIPTION
**Pull request by peterbarry**
Hi all,
 I spent most of the day - getting the simple dbw updates done. 
The implementation generates a constant throttle value, the steering is worked out using the provided YawController. I did not do any research to identify better.

Please review and provide suggestions. 

The car eventually starts to slow down and stop for some reason after a few min. The steering appears to be ok overall. I'll raise an issue for that.

My preferred mode of operation is to review, and update master of its reasonable ok. If there are issues, its best to open them as issues and assign to me if they are my issue... ok?

### CODE REVIEW

**Comment by AntoniaSophia** [comment]
Hi Barry, I had a look at your pull request. Looks really good, great work!!

I could successfully build and run with the simulator in autonomous mode. 
Vehicle runs fine, but is still either too fast or steering has much of latency. At my laptop the vehicle stayed on the road, but it took all the lanes. I guess this was not in scope so far.

Also you proposed procedure is totally fine with me: as soon as the major parts are working fine in a pull request we can merge and create additional issues for fine-tuning.

**Comment by peterbarry** [comment]
@AntoniaSophia , 
 The car stays in the center line on my computer, I'll add some comments in the slack channel.
Peter

**Comment by peterbarry** [comment]
All - can one of you review, I set up to block merges unless its reviewed.

**Comment by peterbarry** [comment]
I turned off review and merged.
Peter

**Pull request merged**
